"""Write operations for Brain wiki: log, raw sources, wiki pages, index, lint, locks, obsidian sync."""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any

from brain_core.paths import system_asset_rel

from .frontmatter import format_frontmatter, parse_frontmatter, validate_date
from .pages import (
    INDEX_EXCLUDED,
    Issue,
    all_page_slugs,
    brain_path,
    existing_page_is_protected,
    extract_wikilinks,
    iter_system_doc_pages,
    iter_wiki_pages,
    normalize_slug,
    raw_ref_to_path,
    read_text,
    today,
    utc_ts,
    wiki_slugs,
    write_text,
)
from .validators import (
    VALID_CURATION,
    VALID_PAGE_TYPES,
    VALID_RAW_TYPES,
    VALID_SOURCE_POLICIES,
    validate_task_refs,
    validate_uiux_stale_references,
)

PAGE_TYPE_LABELS = {
    "concept": "Concepts",
    "entity": "Entities",
    "project": "Projects",
    "decision": "Decisions",
    "source-summary": "Sources",
}

OBSIDIAN_EXPECTED_VIEWS = [
    "brain-pages.base",
    "brain-sources.base",
    "brain-decisions.base",
    "brain-tasks.base",
    "link-graph.canvas",
]


def append_log(brain: Path, operation: str, task_id: str = "", agent_id: str = "", message: str = "") -> None:
    log = brain / "wiki" / "log.md"
    if not log.exists():
        write_text(log, "# Log\n\n")
    with log.open("a", encoding="utf-8") as handle:
        handle.write(f"## [{utc_ts()}] {operation} | {task_id} | {agent_id} | {message}\n")


def write_raw_source(
    brain_value: "str | Path",
    slug: str,
    content: str,
    title: str = "",
    url: str = "",
    source_type: str = "article",
    force: bool = False,
    extra: "dict[str, Any] | None" = None,
) -> Path:
    brain = brain_path(str(brain_value))
    slug = normalize_slug(slug)
    if source_type not in VALID_RAW_TYPES:
        raise ValueError(f"invalid raw type: {source_type}")
    path = brain / "raw" / f"{slug}.md"
    if path.exists() and not force:
        raise FileExistsError(f"raw/{slug}.md already exists")
    fm: dict[str, Any] = {
        "title": title or slug,
        "url": url,
        "type": source_type,
        "fetched": today(),
    }
    if extra:
        fm.update({key: value for key, value in extra.items() if value not in (None, "")})
    write_text(path, format_frontmatter(fm, content))
    return path


def write_wiki_page(
    brain_value: "str | Path",
    slug: str,
    content: str,
    page_type: str = "concept",
    title: str = "",
    tags: "list[str] | None" = None,
    sources: "list[str] | None" = None,
    related: "list[str] | None" = None,
    curation: str = "agent",
    protected: bool = False,
    source_policy: "str | None" = None,
    force: bool = False,
    update_index: bool = False,
) -> Path:
    brain = brain_path(str(brain_value))
    slug = normalize_slug(slug)
    if page_type not in VALID_PAGE_TYPES:
        raise ValueError(f"invalid page type: {page_type}")
    if curation not in VALID_CURATION:
        raise ValueError(f"invalid curation: {curation}")
    policy = source_policy or ("required" if page_type == "source-summary" else "advisory")
    if policy not in VALID_SOURCE_POLICIES:
        raise ValueError(f"invalid source_policy: {policy}")

    source_items = sources or []
    for source in source_items:
        if not raw_ref_to_path(brain, source).exists():
            raise FileNotFoundError(f"missing source: {source}")

    path = brain / "wiki" / f"{slug}.md"
    created = today()
    if path.exists():
        old_fm, _old_body = parse_frontmatter(read_text(path))
        if existing_page_is_protected(old_fm) and not force and curation != "human":
            raise PermissionError(f"wiki/{slug}.md is human-curated/protected")
        created = str(old_fm.get("created") or created)

    fm = {
        "title": title or slug,
        "type": page_type,
        "created": created,
        "updated": today(),
        "curation": curation,
        "protected": protected,
        "source_policy": policy,
        "tags": tags or [],
        "sources": source_items,
        "related": related or [],
    }
    write_text(path, format_frontmatter(fm, content))
    if update_index:
        render_index(brain)
    return path


def render_index(brain_value: "str | Path") -> Path:
    brain = brain_path(str(brain_value))
    wiki = brain / "wiki"
    wiki.mkdir(parents=True, exist_ok=True)
    groups: dict[str, list[str]] = {ptype: [] for ptype in VALID_PAGE_TYPES}
    groups["other"] = []

    for page in iter_wiki_pages(brain):
        fm, _body = parse_frontmatter(read_text(page))
        page_type = str(fm.get("type") or "other")
        if page_type not in groups:
            page_type = "other"
        groups[page_type].append(page.stem)

    lines = [
        "# Wiki Index",
        "",
        "> Generated by brain-lint --fix-index / regenerate_wiki_index.",
        "",
    ]
    for page_type in ("concept", "entity", "project", "decision", "source-summary", "other"):
        slugs = sorted(groups.get(page_type, []))
        if not slugs:
            continue
        lines.append(f"## {PAGE_TYPE_LABELS.get(page_type, 'Other')}")
        lines.extend(f"- [[{slug}]]" for slug in slugs)
        lines.append("")

    path = wiki / "index.md"
    write_text(path, "\n".join(lines).rstrip() + "\n")
    return path


def lock_issues(brain: Path) -> list[Issue]:
    locks = brain / ".locks"
    if not locks.exists():
        return []
    now = int(_dt.datetime.now(_dt.timezone.utc).timestamp())
    issues = []
    for lock_dir in sorted(path for path in locks.iterdir() if path.is_dir()):
        owner = lock_dir / "owner"
        if not owner.exists():
            issues.append(Issue("WARN", str(lock_dir.relative_to(brain)), "lock has no owner file"))
            continue
        parts = read_text(owner).strip().split("|")
        if len(parts) < 3:
            issues.append(Issue("WARN", str(owner.relative_to(brain)), "invalid lock owner format"))
            continue
        agent, epoch, ttl = parts[:3]
        try:
            age = now - int(epoch)
            ttl_value = int(ttl)
        except ValueError:
            issues.append(Issue("WARN", str(owner.relative_to(brain)), "invalid lock timestamp/ttl"))
            continue
        if age > ttl_value:
            issues.append(Issue("WARN", str(lock_dir.relative_to(brain)), f"stale lock by {agent}, age {age}s > ttl {ttl_value}s"))
    return issues


def lint_wiki(brain_value: "str | Path | None" = None) -> list[Issue]:
    brain = brain_path(str(brain_value) if brain_value else None)
    issues = []
    wiki_pages = list(iter_wiki_pages(brain))
    system_pages = iter_system_doc_pages(brain)
    wiki_page_slugs = {page.stem for page in wiki_pages}
    slugs = all_page_slugs(brain)
    inbound: dict[str, set[str]] = {slug: set() for slug in slugs}
    titles: dict[str, list[str]] = {}

    for page in [*wiki_pages, *system_pages]:
        rel = system_asset_rel(page, brain=brain)
        fm, body = parse_frontmatter(read_text(page))
        title = normalize_slug(str(fm.get("title", page.stem)))
        titles.setdefault(title, []).append(page.stem)
        for link in extract_wikilinks(body):
            if link in inbound:
                inbound[link].add(page.stem)
            else:
                issues.append(Issue("WARN", rel, f"missing wikilink target [[{link}]]"))
        updated = fm.get("updated")
        if updated and validate_date(updated):
            age_days = (_dt.date.today() - _dt.date.fromisoformat(str(updated))).days
            if age_days > 180:
                issues.append(Issue("WARN", rel, f"stale page updated {age_days} days ago"))

    for slug, sources in sorted(inbound.items()):
        if (
            slug not in wiki_page_slugs
            or slug in INDEX_EXCLUDED
            or slug.startswith("source-")
            or slug == "review-cycles"
            or slug.startswith("review-cycle-")
        ):
            continue
        if not sources:
            issues.append(Issue("WARN", f"wiki/{slug}.md", "orphan page has no inbound wikilinks"))

    for title, pages in sorted(titles.items()):
        if len(pages) > 1:
            issues.append(Issue("WARN", "wiki", f"possible duplicate title/slug group {title}: {', '.join(sorted(pages))}"))

    issues.extend(validate_task_refs(brain, brain / "tasks" / "active.md", slugs))
    issues.extend(validate_task_refs(brain, brain / "tasks" / "done.md", slugs))
    issues.extend(validate_uiux_stale_references(brain))
    issues.extend(lock_issues(brain))
    return issues


def obsidian_sync_report(brain_value: "str | Path | None" = None) -> "dict[str, Any]":
    """Return sync status of Obsidian views in wiki/_views/.

    Returns a dict with keys:
      ok: bool
      views: list of {name, present, type}
      missing: list of missing view names
      message: human-readable summary
    """
    brain = brain_path(str(brain_value) if brain_value else None)
    views_dir = brain / "wiki" / "_views"
    views = []
    missing = []
    for name in OBSIDIAN_EXPECTED_VIEWS:
        present = (views_dir / name).exists()
        ext = name.rsplit(".", 1)[-1] if "." in name else "unknown"
        views.append({"name": name, "present": present, "type": ext})
        if not present:
            missing.append(name)
    ok = len(missing) == 0
    if ok:
        message = f"OK: all {len(OBSIDIAN_EXPECTED_VIEWS)} Obsidian views present"
    else:
        message = (
            f"WARN: {len(missing)}/{len(OBSIDIAN_EXPECTED_VIEWS)} views missing "
            f"({', '.join(missing)}) — run: brain-index rebuild --with-obsidian"
        )
    return {"ok": ok, "views": views, "missing": missing, "message": message}
