#!/usr/bin/env bash
# build-deb.sh — build dist/brain-runtime_<version>_all.deb from the canonical
# source tree. No fpm, no debhelper, no ruby; only dpkg-deb + fakeroot.
#
# The version is read from pyproject.toml (the single source of truth) and
# checked against debian/changelog. FHS layout:
#   /usr/lib/python3/dist-packages/     the importable brain_* library
#   /usr/share/brain/runtime/{bin,hooks,mcp,schemas,templates}
#   /usr/share/brain/{spec,prd,setup-brain-v2.sh,...}
#   /usr/bin/brain-*                    thin wrappers that exec the real CLI
#
# Usage:
#   bash runtime/packaging/build-deb.sh [--out-dir DIR] [--stage-dir DIR]
#   bash runtime/packaging/build-deb.sh --stage-only --stage-dir DIR   # for debian/rules
set -euo pipefail

REPO_ROOT="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
PACKAGE="brain-runtime"
SHARE="usr/share/brain"                 # data + scripts
BIN_REAL="$SHARE/runtime/bin"           # where the wrappers point

out_dir="$REPO_ROOT/dist"
stage_dir=""
stage_only=0

while [ $# -gt 0 ]; do
  case "$1" in
    --out-dir)     out_dir="$2"; shift 2 ;;
    --stage-dir)   stage_dir="$2"; shift 2 ;;
    --stage-only)  stage_only=1; shift ;;
    -h|--help)     grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *)             echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

for tool in dpkg-deb fakeroot; do
  command -v "$tool" >/dev/null 2>&1 || { echo "FAIL: missing $tool" >&2; exit 3; }
done

# --- version ---------------------------------------------------------------
version="$(sed -nE 's/^version[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' \
  "$REPO_ROOT/pyproject.toml" | head -1)"
[ -n "$version" ] || { echo "FAIL: no version in pyproject.toml" >&2; exit 1; }

changelog_version="$(sed -nE '1s/^brain-runtime \(([^)]+)\).*/\1/p' \
  "$REPO_ROOT/debian/changelog")"
if [ "$changelog_version" != "$version" ]; then
  echo "FAIL: debian/changelog ($changelog_version) != pyproject.toml ($version)" >&2
  echo "      bump debian/changelog to match before building" >&2
  exit 1
fi

# --- stage ----------------------------------------------------------------
if [ -z "$stage_dir" ]; then
  stage_dir="$(mktemp -d)"
  trap 'rm -rf "$stage_dir"' EXIT
fi
root="$stage_dir"
rm -rf "$root"
mkdir -p "$root/$SHARE" "$root/usr/bin" "$root/DEBIAN"

# debian/install: "<src> <dest-dir>". A directory is copied recursively; a src
# ending in "/." copies its contents into <dest-dir> (used for dist-packages).
while read -r src dest; do
  case "$src" in ''|'#'*) continue ;; esac
  mkdir -p "$root/$dest"
  case "$src" in
    */.)  [ -d "$REPO_ROOT/${src%/.}" ] || { echo "FAIL: debian/install names missing $src" >&2; exit 1; }
          cp -a "$REPO_ROOT/$src" "$root/$dest/" ;;
    *)    [ -e "$REPO_ROOT/$src" ] || { echo "FAIL: debian/install names missing $src" >&2; exit 1; }
          cp -a "$REPO_ROOT/$src" "$root/$dest/" ;;
  esac
done < "$REPO_ROOT/debian/install"

# Drop bytecode / caches that may sit in the source tree.
find "$root" -type d -name '__pycache__' -prune -exec rm -rf {} + 2>/dev/null || true
find "$root" -type f -name '*.py[co]' -delete 2>/dev/null || true

# --- /usr/bin wrappers --------------------------------------------------
# BASH_SOURCE inside a script invoked through a symlink points at the symlink,
# so brain-common / ../lib would not resolve. A wrapper that execs the real
# path keeps every CLI's own dirname logic intact. The library is on the
# default sys.path via dist-packages; the MCP dir is not a package, so it is
# named explicitly.
wrapped=0
for cli in "$root/$BIN_REAL"/brain-*; do
  name="$(basename "$cli")"
  [ "$name" = "brain-common" ] && continue      # sourced library, not a CLI
  [ -f "$cli" ] && [ -x "$cli" ] || continue
  cat > "$root/usr/bin/$name" <<EOF
#!/bin/sh
# Generated by build-deb.sh — do not edit.
export PYTHONPATH="/$SHARE/runtime/mcp\${PYTHONPATH:+:\$PYTHONPATH}"
exec "/$BIN_REAL/$name" "\$@"
EOF
  chmod 0755 "$root/usr/bin/$name"
  wrapped=$((wrapped + 1))
done
[ "$wrapped" -gt 0 ] || { echo "FAIL: no CLI wrappers generated" >&2; exit 1; }

# --- DEBIAN/control ---------------------------------------------------
installed_kb="$(du -s -k "$root" | cut -f1)"
field() {  # first single-line value of a field in debian/control
  awk -v f="$1" '$0 ~ "^" f ":" { sub("^" f ":[ \t]*", ""); print; exit }' \
    "$REPO_ROOT/debian/control"
}
depends="$(field Depends | sed 's/,\?[[:space:]]*\${misc:Depends}//')"
maint="$(field Maintainer)"
synopsis="$(field Description)"

{
  echo "Package: $PACKAGE"
  echo "Version: $version"
  echo "Architecture: all"
  echo "Maintainer: $maint"
  echo "Depends: $depends"
  echo "Section: utils"
  echo "Priority: optional"
  echo "Homepage: https://github.com/zhuga79/brain"
  echo "Installed-Size: $installed_kb"
  echo "Description: $synopsis"
  echo " Library in /usr/lib/python3/dist-packages, scripts and templates in"
  echo " /usr/share/brain. Bootstrap a vault with setup-brain-v2.sh."
} > "$root/DEBIAN/control"

if [ "$stage_only" -eq 1 ]; then
  echo "staged $PACKAGE $version at $root ($wrapped wrappers)"
  exit 0
fi

# --- build -----------------------------------------------------------
mkdir -p "$out_dir"
deb="$out_dir/${PACKAGE}_${version}_all.deb"
fakeroot dpkg-deb --build --root-owner-group "$root" "$deb" >/dev/null

echo "built: $deb"
dpkg-deb --info "$deb" | sed 's/^/  /'
echo "contents:"
dpkg-deb --contents "$deb" | awk '{print "  "$NF}' | sort | sed -n '1,20p'
echo "  ... ($(dpkg-deb --contents "$deb" | wc -l) entries)"
